# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- garth-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-paginate

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Prague # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Strange and Unusual # Needed for Siteleaf
    output: true
    description: "a personal archive of sorts" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Strange and Unusual" # Site name or title
logo: "" # Site logo
# favicon: "/favicon.ico" # Uncomment to add custom favicon, or leave as is to use site logo
description: "Hello! I collect many strange stories for my personal database using this blog. If you have a tale to tell, feel free to shoot me a mail at feli.s@seznam.cz" # Site description and default description
url: "https://strangeandunusualblog.netlify.app/" # Site url
baseurl: ""
lang: en-GB
